### ISSUE TITLE
Error to run server with this

### ISSUE THREAD

**Issue by Floridus** [JWebCoder/react-multi-lang#1]
Hello author,

Unfortunately I can not start my server online due to this error.

> node_modules/react-multi-lang/lib/index.js:3
> import * as React from 'react';
> ^^^^^^
> 
> SyntaxError: Unexpected token import

However, I can not have an ES6 code in the node_modules when I run it. That's why I would be glad if you would do gulp.

You should load index.min.js. Run gulp before npm publishing it.

Thank you :)

**Comment by JWebCoder** [comment]
This package uses the babel-preset-react package to transpile the code to the correct version. In what environment are you trying to run this package?
