### ISSUE TITLE
 t is not a function

### ISSUE THREAD

**Issue by MohammadNJ75** [JWebCoder/react-multi-lang#11]
Hello.thanks in advanced for this perfect package:) 
i wanna use this T inside a prop of a component like <Header name={t("menu.title")} /> but it returns an error says TypeError: t is not a function...Thank U for helping

**Comment by JWebCoder** [comment]
@MohammadNJ75 I would need more information. But it seems that you are not using the react hook or the high order component. Please check the example on the repo: [App.tsx](https://github.com/JWebCoder/react-multi-lang/blob/master/example/src/App.tsx)

**Comment by JWebCoder** [comment]
Do you still have an issue or can I close this thread?

**Comment by MohammadNJ75** [comment]
I made it Thank You
