### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by vendemais** [JWebCoder/react-multi-lang#12]
![erroReact](https://user-images.githubusercontent.com/57685094/85315959-54411e00-b492-11ea-86bb-abbf4f6f8a98.png)
![langueErro](https://user-images.githubusercontent.com/57685094/85315964-55724b00-b492-11ea-9917-1630a5954229.png)

**Comment by vendemais** [comment]
@JWebCoder @joaogsleite

**Comment by JWebCoder** [comment]
Hello, vendemais.
You are using react-switch-lang, use react-multi-lang instead or open an issue at [react-switch-lang](https://github.com/narinrit/react-switch-lang)
Also, the error you are getting looks like an error from the bundler and not the module itself.

**Comment by vendemais** [comment]
@JWebCoder what would be a bundle error? I don't have much experience with react

**Comment by JWebCoder** [comment]
@vendemais, can you give us more information about the project? What are you using to build the application? Custom Webpack, create-react-app? Can you share an example repo so that we can replicate the issue?

**Comment by vendemais** [comment]
Zip project 
https://wetransfer.com/downloads/95a4e5b7ead192418f38d566a49386b120200622194830/7c4823

**Comment by JWebCoder** [comment]
Hello again @vendemais, replacing react-switch-lang with react-multi-lang fixes the issue, but you still have a lot more errors on the application.
I'm closing this since this is not an issue with the react-multi-lang package.
If you have a problem with the package, feel free to open another issue.
