### ISSUE TITLE
setLanguage Does rerender too many times

### ISSUE THREAD

**Issue by VrTech** [JWebCoder/react-multi-lang#13]
How can I solve setLanguage? When I trigger this function, it renders to many times and get an error

Unhandled Runtime Error
Error: Too many re-renders. React limits the number of renders to prevent an infinite loop.

**Comment by JWebCoder** [comment]
Hello @VrTech, the multiple renders are not related to to the lib, there must be some infinite state cycle on your side.

**Comment by VrTech** [comment]
Thank you for your reply.
